---
#
# generate ans exec docker image via docker compose
#
# support only systemD
#
# TODO: make docker-compose install
#

- file: state=directory path={{ item }}  owner=root group=docker mode=755
  sudo: yes
  with_items:
    - /etc/docker-compose/{{ docker_app_name }}

- template: src={{ docker_compose_file }} dest=/etc/docker-compose/{{ docker_app_name }}/docker-compose.yml
  sudo: yes

- template: src=parameters.j2 dest=/etc/sysconfig/docker-compose-{{ docker_app_name }}
  sudo: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- template: src=parameters.j2 dest=/etc/default/docker-compose-{{ docker_app_name }}
  sudo: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


- template: src=docker-compose-permanent.j2 dest="/lib/systemd/system/docker-compose-permanent@.service"
  sudo: yes

- file: src="/lib/systemd/system/docker-compose-permanent@.service" dest="/lib/systemd/system/docker-comopose-permanent@{{ docker_app_name }}.service"  state=link force=yes
  sudo: yes

- service: name="docker-compose-permanent@{{ docker_app_name }}.service" enabled=yes state=restarted

